# Generated by Django 3.0.5 on 2021-03-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210327_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_setup',
            name='height1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient_setup',
            name='height2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient_setup',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
