# Generated by Django 3.0.5 on 2021-02-23 05:56

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication_master',
            fields=[
                ('medication_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('medication_name', models.CharField(max_length=500)),
                ('medication_unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Medication_master',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
            ],
            options={
                'db_table': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_reading', models.IntegerField(blank=True, null=True)),
                ('weight_unit', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=100)),
                ('question2', models.CharField(max_length=100)),
                ('question3', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_setup', to='patients.Patients')),
            ],
            options={
                'db_table': 'Patient_Setup',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_input_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('frequency', models.CharField(max_length=100)),
                ('currently_taking', models.BooleanField(default=0)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='patients.Medication_master')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medication', to='patients.Patients')),
            ],
            options={
                'db_table': 'Medication',
            },
        ),
        migrations.CreateModel(
            name='Glucose_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_reading', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_glucose', to='patients.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='Blood_pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_reading', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patients')),
            ],
        ),
    ]
