# Generated by Django 3.0.5 on 2021-02-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucose_level',
            name='glucose_reading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
