# Generated by Django 3.0.5 on 2021-02-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210223_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='patient',
            new_name='patients',
        ),
        migrations.AlterField(
            model_name='glucose_level',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patients'),
        ),
    ]
