# Generated by Django 3.0.5 on 2021-03-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20210323_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_setup',
            old_name='lower_bound',
            new_name='glucose_lower_limit',
        ),
        migrations.RenameField(
            model_name='patient_setup',
            old_name='upper_bound',
            new_name='glucose_upper_limit',
        ),
        migrations.RemoveField(
            model_name='patient_setup',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='patient_setup',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='patient_setup',
            name='question3',
        ),
        migrations.AddField(
            model_name='patient_setup',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient_setup',
            name='height1',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient_setup',
            name='height2',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient_setup',
            name='height_unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient_setup',
            name='sex',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient_setup',
            name='weight',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient_setup',
            name='weight_unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
