# Generated by Django 3.0.5 on 2021-02-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_users_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_pressure',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='glucose_level',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user_setup',
            old_name='user',
            new_name='user_id',
        ),
    ]
