# Generated by Django 3.0.5 on 2021-02-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210218_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_pressure',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='glucose_level',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_setup',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='weight',
            old_name='user_id',
            new_name='user',
        ),
    ]
