# Generated by Django 3.0.5 on 2021-02-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210223_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='patients',
            new_name='patient',
        ),
    ]
