# Generated by Django 3.0.5 on 2021-03-04 02:28

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210223_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medication_image',
            field=models.ImageField(default='posts/default.jpg', max_length=255, upload_to=patients.models.upload_to),
        ),
        migrations.AlterField(
            model_name='glucose_level',
            name='date',
            field=models.DateField(default='2021-03-03'),
        ),
        migrations.AlterField(
            model_name='glucose_level',
            name='timestamp',
            field=models.TimeField(default='21:28:03'),
        ),
    ]
