# Generated by Django 3.0.5 on 2021-02-18 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210218_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='medication_id',
            new_name='medication',
        ),
    ]
