# Generated by Django 3.0.5 on 2021-03-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20210303_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_setup',
            name='lower_bound',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='patient_setup',
            name='upper_bound',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='glucose_level',
            name='date',
            field=models.DateField(default='2021-03-04'),
        ),
        migrations.AlterField(
            model_name='glucose_level',
            name='timestamp',
            field=models.TimeField(default='01:56:59'),
        ),
    ]
