# Generated by Django 3.0.5 on 2021-03-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20210304_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucose_level',
            name='timestamp',
            field=models.TimeField(default='01:57:48'),
        ),
    ]
