# Generated by Django 3.0.5 on 2021-03-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20210304_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucose_level',
            name='timestamp',
            field=models.TimeField(default='02:22:59'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
