# Generated by Django 3.0.5 on 2021-03-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20210326_0104'),
        ('auth', '0011_update_proxy_permissions'),
        ('knox', '0008_auto_20210326_0104'),
        ('patients', '0009_auto_20210320_0312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patients',
            new_name='CustomUser',
        ),
        migrations.RenameModel(
            old_name='Patient_Setup',
            new_name='User_Setup',
        ),
        migrations.AlterField(
            model_name='glucose_level',
            name='date',
            field=models.DateField(default='2021-03-26'),
        ),
        migrations.AlterField(
            model_name='glucose_level',
            name='timestamp',
            field=models.TimeField(default='01:04:08'),
        ),
    ]
