# Generated by Django 3.0.5 on 2021-03-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20210326_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucose_level',
            name='date',
            field=models.DateField(default='2021-03-27'),
        ),
        migrations.AlterField(
            model_name='glucose_level',
            name='timestamp',
            field=models.TimeField(default='16:23:01'),
        ),
    ]
