# Generated by Django 3.0.5 on 2021-04-05 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import patients.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('patient_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Medication_master',
            fields=[
                ('medication_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('medication_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Medication_master',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_reading', models.IntegerField(blank=True, null=True)),
                ('weight_unit', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=20, null=True)),
                ('height1', models.IntegerField(null=True)),
                ('height1_unit', models.CharField(max_length=20, null=True)),
                ('height2', models.IntegerField(null=True)),
                ('height2_unit', models.CharField(max_length=20, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('weight_unit', models.CharField(max_length=20, null=True)),
                ('glucose_lower_limit', models.FloatField(null=True)),
                ('glucose_upper_limit', models.FloatField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_setup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Patient_Setup',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_input_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=patients.models.upload_to)),
                ('dosage', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('frequency_period', models.CharField(max_length=100, null=True)),
                ('currently_taking', models.BooleanField(default=0)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='patients.Medication_master')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medication', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Medication',
            },
        ),
        migrations.CreateModel(
            name='Glucose_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_reading', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_reading', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auth_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
