# Generated by Django 3.0.5 on 2021-04-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_pressure',
            old_name='bp_reading',
            new_name='diastolic',
        ),
        migrations.AddField(
            model_name='blood_pressure',
            name='systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Auth_token',
        ),
    ]
