# Generated by Django 3.0.5 on 2021-03-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210327_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_setup',
            old_name='height_unit',
            new_name='height1_unit',
        ),
        migrations.AddField(
            model_name='patient_setup',
            name='height2_unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
