# Generated by Django 3.0.5 on 2021-03-31 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20210327_2126'),
        ('patients', '0003_customuser_user_permissions'),
    ]

    operations = [
    ]
